### ISSUE TITLE
Route update causes issues

### ISSUE THREAD

**Issue by fahlmant** [openshift/operator-custom-metrics#11]
The route update  for an existing route is giving the following:
```
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2019-07-23T13:47:57Z
        message: route pagerduty-operator already exposes pagerduty-operator-pagerduty-operator.c39b.hive-stage.openshiftapps.com
          and is older
        reason: HostAlreadyClaimed
        status: "False"
        type: Admitted
      host: pagerduty-operator-pagerduty-operator.c39b.hive-stage.openshiftapps.com
      routerName: router
```
The route continues to exist but does not work.
